* emms-player-mpv-jp-radios

** What is it ?

   This provides EMMS ( [[https://www.gnu.org/software/emms/][The Emacs Multimedia System]] ) simple players for Japan radio stations.

   + Radiko ( [[http://radiko.jp/]] )
   + らじる★らじる ( [[http://www3.nhk.or.jp/netradio/]] )
   + 超!A&G+ ( [[http://www.agqr.jp/]] )
   + インターネットラジオステーション〈音泉〉( [[http://www.onsen.ag/]] )
   + 響 - HiBiKi Radio Station - ( [[http://hibiki-radio.jp/]] )

   The above radio stations are available only in Japan.

** Requirements

   + GNU Emacs 24 or later
   + EMMS 4.0
   + mpv v0.7 or later ( [[https://github.com/mpv-player/mpv]] )
     + ffmpeg (the build with –enable-librtmp (for Radiko))
   + emms-palyer-simple-mpv ( [[https://github.com/momomo5717/emms-player-simple-mpv]] )
   + wget (for Radiko)
   + swftools (for Radiko)

   Tested with GNU Emacs 24.5 (emacs-mac-app @5.7_0), EMMS 4.0, mpv @0.8.3_2.

** Setup

   #+BEGIN_SRC emacs-lisp
     (add-to-list 'load-path "/path/to/emms-player-mpv-jp-radios")
     (require 'emms-player-mpv-jp-radios)
   #+END_SRC
   
   + Adding all EMMS jp radio players

     #+BEGIN_EXAMPLE emacs-lisp
       (emms-player-mpv-jp-radios-add-all)     
     #+END_EXAMPLE

   + Adding separetely

     + Radiko

       #+BEGIN_SRC emacs-lisp
         (emms-player-mpv-jp-radios-add-radiko)       
       #+END_SRC

       =emms-player-mpv-radiko= cannot use =emms-seek= and =emms-seek-to=,
       because mpv cannot seek while playing Radiko.

     + らじる★らじる
       
       #+BEGIN_SRC emacs-lisp
         (emms-player-mpv-jp-radios-add-radiru)       
       #+END_SRC

     + 超!A&G+

       #+BEGIN_SRC emacs-lisp
         (emms-player-mpv-jp-radios-add-agqr)       
       #+END_SRC

     + インターネットラジオステーション〈音泉〉

       #+BEGIN_SRC emacs-lisp
         (emms-player-mpv-jp-radios-add-onsen)       
       #+END_SRC

     + 響 - HiBiKi Radio Station -

       #+BEGIN_SRC emacs-lisp
         (emms-player-mpv-jp-radios-add-hibiki)       
       #+END_SRC

** Usage

   Each emms streams package provides a function to add streams to =*EMMS Streams*= buffer.

   #+BEGIN_SRC
   M-x emms-streams
   M-x emms-stream-serviceName-add-bookmark
   #+END_SRC

** References

   + How to play Radiko
     + rec_radiko.sh ( [[https://gist.github.com/saiten/875864]] )
   + How to play 響 - HiBiKi Radio Station -
     + [[http://vector.hateblo.jp/entry/2015/01/03/193556]]

