[[http://melpa.org/#/emms-player-mpv-jp-radios][file:http://melpa.org/packages/emms-player-mpv-jp-radios-badge.svg]]

* emms-player-mpv-jp-radios

** What is it ?

   This provides EMMS ( [[https://www.gnu.org/software/emms/][The Emacs Multimedia System]] ) simple players for Japan radio stations.

   + Radiko ( [[http://radiko.jp/]] )
   + らじる★らじる ( [[http://www3.nhk.or.jp/netradio/]] )
   + 超!A&G+ ( [[http://www.agqr.jp/]] )
   + インターネットラジオステーション〈音泉〉( [[http://www.onsen.ag/]] )
   + 響 - HiBiKi Radio Station - ( [[http://hibiki-radio.jp/]] )

   The above radio stations are available only in Japan.

** Requirements

   + GNU Emacs 24 or later
   + EMMS 4.0
   + mpv v0.7 or later ( [[https://github.com/mpv-player/mpv]] )
     + ffmpeg ( the build with –enable-librtmp (for Radiko) )
   + emms-palyer-simple-mpv ( [[https://github.com/momomo5717/emms-player-simple-mpv]] )
   + wget (for Radiko)
   + swftools (for Radiko)

   Tested with GNU Emacs 24.5 (emacs-mac-app @5.7_0), EMMS 4.0, mpv @0.8.3_2.

** Setup

   #+BEGIN_SRC emacs-lisp
     (let ((default-directory "/path/to/emms-player-mpv-jp-radios"))
       (add-to-list 'load-path default-directory)
       (normal-top-level-add-subdirs-to-load-path))

     (require 'emms-player-mpv-jp-radios)
   #+END_SRC

   + Adding all EMMS jp radio players

     #+BEGIN_EXAMPLE emacs-lisp
       (emms-player-mpv-jp-radios-add-all)
     #+END_EXAMPLE

   + Adding separately

     Function: =emms-player-mpv-jp-radios-add &rest names=

     =names= is as follows.

     + "radiko" (Radiko)
     + "radiru" (らじる★らじる)
     + "agqr"   (超!A&G+)
     + "onsen"  (インターネットラジオステーション〈音泉〉)
     + "hibiki" (響 - HiBiKi Radio Station -)

     #+BEGIN_SRC emacs-lisp
       ;; An example of setting only for Radiko and らじる★らじる
       (emms-player-mpv-jp-radios-add "radiko" "radiru")
     #+END_SRC

** Usage

   Each emms streams package provides a function to add streams to =*EMMS Streams*= buffer.

   #+BEGIN_SRC
   M-x emms-streams
   ;; serviceName is radiko, radiru, etc.
   M-x emms-stream-serviceName-add-bookmark
   #+END_SRC

** References

   + How to play Radiko
     + rec_radiko.sh ( [[https://gist.github.com/saiten/875864]] )
   + How to play 響 - HiBiKi Radio Station -
     + [[http://vector.hateblo.jp/entry/2015/01/03/193556]]
